import { useAccount } from 'wagmi'

import styles from '../styles/Home.module.css'

export default function Home() {
  const { address } = useAccount()
  return (
    <>
      <title>Create Next App</title>
      <meta name='description' content='Generated by create next app' />
      <meta name='viewport' content='width=device-width, initial-scale=1' />
      <link rel='icon' href='/favicon.ico' />

      <main className={styles.main}>
        <div className={styles.description}>
          <p>
            Get started by editing&nbsp;
            <code className={styles.code}>pages/index.tsx</code>
          </p>
          <div></div>
        </div>

        <div className={styles.center}></div>
      </main>
    </>
  )
}
